"""add role field to user

Revision ID: 162a147c8e3e
Revises: d20f01d8d0bb
Create Date: 2018-07-01 03:54:59.744158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162a147c8e3e'
down_revision = 'd20f01d8d0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_timestamp'), 'job', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('role', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_index(op.f('ix_job_timestamp'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
